package model;
import java.util.*;

import model.GraphNode;

/**
*    @Author Harrison Boyle-Thomas
*    @Date 02/28/21
**/
public class EdgeComparator implements Comparator<GraphEdge>{

    /**
    *    @Param mapIn = the distance map generated by DSP
    **/
    public EdgeComparator(){

    }

    /**
    *    @a operand one
    *    @b operand two
    *    @return -1 if the weight(a) < weight(b) from the
    **/
    public int compare(GraphEdge a, GraphEdge b){
        int weightOfA = a.getLength();
        int weightOfB = b.getLength();
        if(weightOfA == weightOfB){
            return 0;
        }
        if(weightOfA < weightOfB){
            return -1;
        }
        return 1;
    }
}
